controller_list:
  - name: vs060
    action_ns: "position_trajectory_controller/follow_joint_trajectory"
    type: FollowJointTrajectory 
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - flange