#!/usr/bin/env bash

#install gazebo_ros_packages
apt-get install ros-kinetic-gazebo-ros-pkgs ros-kinetic-gazebo-ros-control

#Source the setup bash
source ~/catkin_ws/devel/setup.bash

if [ $? -eq 0 ]; then
    echo "OK"
else 
    echo "FAIL"
fi

#source alias
source ./aliases

#Add alises into bash
cat ./aliases >> ~/.bashrc

#reload bash
#exec bash


